- name: open firewall ports
  lineinfile:
    dest=/etc/sysconfig/iptables
    state=present
    regexp="-A RH-Firewall-1-INPUT -p tcp -m state --state NEW -m tcp --dport {{ item }} -j ACCEPT" 
    insertafter="-A RH-Firewall-1-INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT"
    line="-A RH-Firewall-1-INPUT -p tcp -m state --state NEW -m tcp --dport {{ item }} -j ACCEPT"
  notify: restart iptables
  with_items:
    - 80
    - 443